modLoader="javafml"
loaderVersion="[${forge_version_major},)"
license="MIT"
issueTrackerURL="https://github.com/Ephys/mc-fundamental/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Fundamental"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/Ephys/mc-fundamental"
logoFile="examplemod.png"
credits="Thanks for this example mod goes to Java"
authors="Ephys, FlandersAustin"
description='''
'''
[[dependencies.fundamental]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fundamental]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},${mc_version_next_major})"
    ordering="NONE"
    side="BOTH"
[[dependencies.fundamental]]
    modId="cookiecore"
    mandatory=true
    versionRange="[3.3.0,)"
    ordering="AFTER"
    side="BOTH"
