modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Ephys/mc-fundamental/issues"
[[mods]]
modId="fundamental"
version="${file.jarVersion}"
displayName="Fundamental"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/Ephys/mc-fundamental"
logoFile="logo.png"
credits=""
authors="Ephys, FlandersAustin"
description='''
'''
[[dependencies.fundamental]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fundamental]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fundamental]]
    modId="cookiecore"
    mandatory=true
    versionRange="[1.18.2-4.0.0,)"
    ordering="AFTER"
    side="BOTH"
